### ISSUE TITLE
ㅁㄴㅇ

### ISSUE THREAD

**Issue by nsun9505** [yoon1fe/Algorithm_Study#1]
![image](https://user-images.githubusercontent.com/43994964/106551822-666f5880-6559-11eb-9ba6-c147fe26a5e4.png)

**Comment by nsun9505** [comment]
![image](https://user-images.githubusercontent.com/43994964/106551851-7a1abf00-6559-11eb-8955-c6c50bb07501.png)

**Comment by yoon1fe** [comment]
?? 뭔가요 이게

**Comment by nsun9505** [comment]
순위탐색 문자열로 풀었을 때랑 객체 따로 만들어서 풀었을 때입니당

**Comment by yoon1fe** [comment]
멋지네요 !!
